language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-asio-dev
script:
  - mkdir -p build
  - cd build
  - make all
  - test_all
  - cd ..
