language: cpp
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev
script:
  - mkdir -p build || exit $?
  - cd build || exit $?
  - cmake .. || exit $?
  - make all || exit $?
  - test_all || exit $?
  - cd .. || exit $?
